import localFont from "next/font/local";
import "../globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../../theme';
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});


const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,
  params: {locale} }) {
    const messages = await getMessages();
  return (
    <html  lang={locale}>
        <body className={roboto.variable}>
      <AppRouterCacheProvider options={{ key: 'css' }}>
        <ThemeProvider theme={theme} >
        <NextIntlClientProvider messages={messages}>

        {children}
        </NextIntlClientProvider>
        </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
